### PR TITLE
Fix for the player tab crash

### PR DESCRIPTION
**Pull request by colmalle**
There is a problem when opening the players list the game crashes because the subList toIndex is higher than the list size.

### CODE REVIEW

**Comment by Snacks199** [comment]
how do i fix it

**Comment by colmalle** [comment]
You can look at the change. Change it in your own workspace and rebuild.

> how do i fix it

**Review by iKJStreepp — COMMENTED** [review]
hola como lo arreglo

**Comment by WeeabooOtaku** [comment]
I dont understand what to do

**Review by ElGooseMan — APPROVED** [review]

**Review by WeeabooOtaku — APPROVED** [review]

**Comment by colmalle** [comment]
> I dont understand what to do

You can look in the [update](https://github.com/TrvsF/wurstplus-two/pull/37/commits/d1da8693acf79966f49937dff81cb44138f763d3). Change it and rebuild.

**Pull request merged**
